# Generated by Django 5.2.1 on 2025-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='img')),
                ('context', models.TextField()),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'Service',
                'managed': True,
            },
        ),
    ]
