# Generated by Django 5.2.1 on 2025-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.CharField(max_length=50),
        ),
    ]
