# Generated by Django 5.2.1 on 2025-06-08 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth-building', 'Wealth Building'), ('income', 'Generate Income'), ('education', 'Education Funding'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Get Started Submission',
                'verbose_name_plural': 'Get Started Submissions',
                'db_table': 'Get Started Submission',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
