# Generated by Django 5.2.1 on 2025-06-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0005_consultationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='additional_notes',
            field=models.TextField(blank=True, default='True'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='investment_amount',
            field=models.CharField(blank=True, choices=[('under_10k', 'Under $10,000'), ('10k_50k', '$10,000 - $50,000'), ('50k_100k', '$50,000 - $100,000'), ('100k_250k', '$100,000 - $250,000'), ('250k_500k', '$250,000 - $500,000'), ('over_500k', 'Over $500,000')], default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='investment_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='preferred_contact_time',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (9AM-12PM)'), ('afternoon', 'Afternoon (12PM-5PM)'), ('evening', 'Evening (5PM-8PM)')], max_length=20),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='step_completed',
            field=models.IntegerField(default=1),
        ),
    ]
