# Generated by Django 5.2.1 on 2025-06-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0006_consultationrequest_additional_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='investment_experience',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='preferred_contact_method',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='preferred_contact_time',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='step_completed',
        ),
    ]
