# Generated by Django 5.2.1 on 2025-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0007_remove_consultationrequest_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(default='av.png', upload_to='logo'),
        ),
    ]
