# Generated by Django 5.2.1 on 2025-06-10 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0008_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('income', 'Income Generation'), ('education', 'Education Funding'), ('other', 'Other')], max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=15)),
                ('investment_amount', models.CharField(choices=[('10000-50000', '$1,000 - $5,000'), ('50000-100000', '$10,000 - $50,000'), ('100000-500000', '$50,000 - $100,000'), ('500000+', '$100,000+')], max_length=20)),
                ('services', models.JSONField(blank=True, default=list)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
