# Generated by Django 5.2.1 on 2025-06-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0009_investmentapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentapplication',
            name='investment_amount',
            field=models.CharField(choices=[('1000-5000', '$1,000 - $5,000'), ('10000-50000', '$10,000 - $50,000'), ('50000-100000', '$50,000 - $100,000'), ('10000-500000', '$100,000 - $500,000'), ('500000+', '$500,000+')], max_length=20),
        ),
    ]
