# Generated by Django 5.2.1 on 2025-06-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0011_alter_investmentapplication_investment_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestmentApplication',
        ),
    ]
