# Generated by Django 5.2.1 on 2025-06-11 18:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0012_delete_investmentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('income', 'Income Generation'), ('education', 'Education Funding'), ('other', 'Other')], max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('investment_amount', models.CharField(choices=[('10000-50000', '$1,000 - $5,000'), ('50000-100000', '$10,000 - $50,000'), ('100000-500000', '$50,000 - $100,000'), ('500000+', '$100,000+')], max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('contacted', 'Client Contacted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'onboarding_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_id'], name='onboarding__referen_396756_idx'), models.Index(fields=['email'], name='onboarding__email_52d6f0_idx'), models.Index(fields=['status'], name='onboarding__status_56da6e_idx'), models.Index(fields=['created_at'], name='onboarding__created_4787f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('portfolio-management', 'Portfolio Management'), ('wealth-planning', 'Wealth Planning'), ('tax-optimization', 'Tax Optimization'), ('estate-planning', 'Estate Planning')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='alpicap.onboardingapplication')),
            ],
            options={
                'db_table': 'service_interests',
                'unique_together': {('application', 'service_type')},
            },
        ),
    ]
