# Generated by Django 5.2.1 on 2025-06-12 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0013_onboardingapplication_serviceinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Onboarding Application', 'verbose_name_plural': 'Onboarding Applications'},
        ),
        migrations.AlterField(
            model_name='onboardingapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onboardingapplication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='onboardingapplication',
            name='risk_tolerance',
            field=models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=15),
        ),
        migrations.CreateModel(
            name='ApplicationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('portfolio-management', 'Portfolio Management'), ('wealth-planning', 'Wealth Planning'), ('tax-optimization', 'Tax Optimization'), ('estate-planning', 'Estate Planning')], max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='alpicap.onboardingapplication')),
            ],
            options={
                'verbose_name': 'Application Service',
                'verbose_name_plural': 'Application Services',
                'db_table': 'application_services',
                'unique_together': {('application', 'service_type')},
            },
        ),
        migrations.DeleteModel(
            name='ServiceInterest',
        ),
    ]
