# Generated by Django 5.2.1 on 2025-06-13 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0014_alter_onboardingapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('income', 'Income Generation'), ('education', 'Education Funding'), ('other', 'Other')], max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=15)),
                ('investment_amount', models.CharField(choices=[('500-1500', '$500 - $1,500'), ('2500-5500', '$2,500 - $5,500'), ('6000-10000', '$6,000 - $10,000'), ('10000-40000', '$10,000 - $40,000'), ('50000-100000', '$50,000 - $100,000'), ('100000+', '$100,000+')], max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('contacted', 'Client Contacted')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment Application',
                'verbose_name_plural': 'Investment Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='applicationservice',
            options={},
        ),
        migrations.RenameField(
            model_name='applicationservice',
            old_name='service_type',
            new_name='service',
        ),
        migrations.AlterModelTable(
            name='applicationservice',
            table=None,
        ),
        migrations.AlterUniqueTogether(
            name='applicationservice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='applicationservice',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='alpicap.investmentapplication'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationservice',
            unique_together={('application', 'service')},
        ),
        migrations.DeleteModel(
            name='OnboardingApplication',
        ),
    ]
