# Generated by Django 5.2.1 on 2025-06-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0015_investmentapplication_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationService',
        ),
        migrations.DeleteModel(
            name='InvestmentApplication',
        ),
    ]
