# Generated by Django 5.2.1 on 2025-06-14 16:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0017_acceptanceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('income', 'Income Generation'), ('education', 'Education Funding'), ('other', 'Other')], max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('investment_amount', models.CharField(choices=[('500-1500', '$500 - $1,500'), ('2500-5500', '$2,500 - $5,500'), ('6000-10000', '$6,000 - $10,000'), ('10000-40000', '$10,000 - $40,000'), ('50000-100000', '$50,000 - $100,000'), ('100000+', '$100,000+')], max_length=20)),
                ('services', models.TextField(blank=True, help_text='Comma-separated list of selected services')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(max_length=50, unique=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Under Review'), ('approved', 'Approved'), ('contacted', 'Client Contacted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
            ],
            options={
                'verbose_name': 'Investment Application',
                'verbose_name_plural': 'Investment Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('form_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='AcceptanceForm',
        ),
    ]
