# Generated by Django 5.2.1 on 2025-06-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0018_application_formsession_delete_acceptanceform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('income', 'Income Generation'), ('education', 'Education Funding'), ('other', 'Other')], max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('investment_amount', models.CharField(choices=[('500-1500', '$500 - $1,500'), ('2500-5500', '$2,500 - $5,500'), ('6000-10000', '$6,000 - $10,000'), ('10000-40000', '$10,000 - $40,000'), ('50000-100000', '$50,000 - $100,000'), ('100000+', '$100,000+')], max_length=20)),
                ('services', models.TextField(blank=True, help_text='Comma-separated list of services', null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acceptance Form',
                'verbose_name_plural': 'Acceptance Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='FormSession',
        ),
    ]
