# Generated by Django 5.2.1 on 2025-06-15 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0019_acceptanceform_delete_application_delete_formsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('investment_goal', models.CharField(choices=[('retirement', 'Retirement Planning'), ('wealth', 'Wealth Building'), ('income', 'Income Generation'), ('education', 'Education Funding'), ('other', 'Other')], max_length=20)),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=15)),
                ('investment_amount', models.CharField(choices=[('500-1500', '$500 - $1,500'), ('2500-5500', '$2,500 - $5,500'), ('6000-10000', '$6,000 - $10,000'), ('10000-40000', '$10,000 - $40,000'), ('50000-100000', '$50,000 - $100,000'), ('100000+', '$100,000+')], max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('reference_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investment Application',
                'verbose_name_plural': 'Investment Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('portfolio-management', 'Portfolio Management'), ('wealth-planning', 'Wealth Planning'), ('tax-optimization', 'Tax Optimization'), ('estate-planning', 'Estate Planning')], max_length=30)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='alpicap.investmentapplication')),
            ],
            options={
                'verbose_name': 'Application Service',
                'verbose_name_plural': 'Application Services',
                'unique_together': {('application', 'service_type')},
            },
        ),
    ]
