# Generated by Django 5.2.1 on 2025-06-15 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0020_investmentapplication_applicationservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptanceform',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
