# Generated by Django 5.2.1 on 2025-06-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpicap', '0021_alter_acceptanceform_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationService',
        ),
        migrations.DeleteModel(
            name='InvestmentApplication',
        ),
    ]
